Add some types to _mathtext.py
Mypy 1.16.0 flags errors here:

lib/matplotlib/_mathtext.py:2531: error: "Node" has no attribute "width"  [attr-defined]
lib/matplotlib/_mathtext.py:2608: error: List item 0 has incompatible type "Kern"; expected "Hlist | Vlist"  [list-item]

The check for the attribute _metrics is equivalent to checking for an
instance of Char, since only Char and its subclasses set self._metrics.

Mypy infers an unnecessarily tight type list[Hlist | Vlist] for
spaced_nucleus so we give it a more general one.