Suppress exception chaining in FontProperties.
For `FontProperties(stretch=12345)`; before:
```
Traceback (most recent call last):
  File ".../matplotlib/font_manager.py", line 888, in set_stretch
    raise ValueError()
ValueError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../matplotlib/font_manager.py", line 695, in __init__
    self.set_stretch(stretch)
  File ".../matplotlib/font_manager.py", line 891, in set_stretch
    raise ValueError("stretch is invalid") from err
ValueError: stretch is invalid
```
after
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../matplotlib/font_manager.py", line 695, in __init__
    self.set_stretch(stretch)
  File ".../matplotlib/font_manager.py", line 900, in set_stretch
    raise ValueError(f"{stretch=} is invalid")
ValueError: stretch=12345 is invalid
```