Add compilers to conda environment
This fixes issues with `libstdc++.so` when using a system with a newer
compiler. In such cases, the compiler will create links to new symbols,
but the shared library available at runtime from conda-forge will not
have them available.

This results in errors such as:
```
ImportError: /home/elliott/micromamba/envs/mpl-dev/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.15' not found (required by /home/elliott/code/matplotlib/build/cp39/src/_c_internal_utils.cpython-39-x86_64-linux-gnu.so)
```