Update wx backend to be compatible with wxPython classic 2.8.12+ on Py2.7+ and Phoenix Py2.7+ and 3.4+
Squashed the following commits:
- set a variable at import time for wxPython classic/phoenix version
- only use wxversion in Py2
- remove BeginDrawing/EndDrawing
- remove wx.WXK_ PRIOR, NEXT, NUMPAD_PRIOR, NUMPAD_NEXT as deprecated for a long time

- use wxversion only in Py2
- make it work on Py2.7 with wxPython 2.8.12, 2.9.5 and 3.0.2Phoenix
- make it work on Py3.4 with 3.0.2Phoenix

Conflicts:
	examples/user_interfaces/embedding_in_wx2.py

- sometimes get an except: builtins.AttributeError: 'App' object has no attribute 'ProcessIdle'
- use wxversion only in Py2
- make it work on Py2.7 with wxPython 2.8.12, 2.9.5 and 3.0.2Phoenix
- make it work on Py3.4 with 3.0.2Phoenix

Conflicts:
	examples/user_interfaces/fourier_demo_wx.py

- revert incorrect change
- use FileDialog styles which work for 2.8+

- move version specific stuff to wx_compat.py
- PEP8 the code

- pep8 lines to long

- Skip is needed with wx backend and 2.8.12 to have Frame close

- OnPaint event is handled by the backend, not needed here

- Begin/EndDrawing is not needed

- remove backend_wx and backend_wxagg from PEP8 from EXPECTED_BAD_FILES

- clean up of examples, tested with wxPython 2.8.12.1, 3.0.1.1, Phoenix 3.0.2.dev77483 both for 'WX' and 'WXAgg' backends
- remove special casing of toolbar for WXMAC, if necessary put it back in but check WXMAC version as it does not work in 10.9

- make 'WX' and 'WXAgg' work with wxPython 2.8, 2.9, 3.0 and 3.0.2 Phoenix

- PEP8'ify

- revert the EVT_PAINT handler

- remove print lines
- make use of wxversion optional

- remove blank line after class added by autopep8

- fix blank after class and too excessive line split done by autopep8

- remove extraneous blank line

- remove unneeded comma

- some more autopep8 clean up

- some more autopep8 clean up

- m_keyCode is deprecated an no longer available as of 2.9

- pep8'ify to satisfy Travis CI

- always get alpha, so same works in 2.8 and Phoenix

- more descriptive name

- adapt to wx_compat.py

- fix deprecation for wx.StockCursor
- statusBar.SetFieldsCount is not necessary and causes a two short field
- add version select comment

- add StockCursor rename

- pep8 corrections

use .Bind

use .Bind, but keep AddSimpleTool as AddTool is a Phoenix addition

improve comment

remove redundant import

clean up

clean up
minimal version check only in wx_compat.py

rename method

use distutils for version comp

up wx version for Sphinx doc mocking

clean up imports

backend_version is now in wx_compat

Oops, Toolbar is used in backends.__init__

fix PEP8 whitespace

fix line splitting

clean up