Improve error when passing 0d array to scatter().
With `scatter([1, 2], [3, 4], c=np.array(.5))`...

previously:

    <elided>
      File ".../matplotlib/colors.py", line 338, in to_rgba_array
        if len(c) == 0:
    TypeError: len() of unsized object

now

    <elided>
      File ".../matplotlib/axes/_axes.py", line 4249, in _parse_scatter_color_args
        raise invalid_shape_exception(c.size, xsize)
    ValueError: 'c' argument has 1 elements, which is inconsistent with 'x' and 'y' with size 2.

Essentially the problem is that np.array(.5) passes an
`isinstance(..., Iterable)` check (which only checks the type) but
np.iterable() more correctly returns False because it actually tries to
iter on it.