Remove toplevel unit/ directory.
- Move `memleak.py` and `compare_backend_driver_result.py` to tools/.
  Removed some Py2 workarounds there.

- `ellipse_large.py` currently fails with

    RuntimeError: adjustable='datalim' is not allowed when both axes are shared.

  IOW we're not even bothering keeping it up to date, so remove it.

- `legend_unit.py` is basically covered by `test_legend.py`.

- `longs_test.py` should be covered by
  `test_simplification.py::test_overflow`.

- `mlab_unit.py` has never been ported to Py3 (`import StringIO`), and most of
  mlab is on its way out anyways, so remove it.

- `threading_test.py` could be converted into a proper unit test but it
  would be a rather slow one (checking that there is no race condition
  by running a bunch of iterations) so I'd rather not do it unless it
  turns out we're reintroducing race conditions.