Test marker=MarkerStyle instance
Creating markers from MarkerStyle and passing them to axes could cause
both `plot` and `errorbar` to raise

```
TypeError: float() argument must be a string or a number, not 'MarkerStyle'
```

in 3.2.2, as found in #18600 and discussed in the comments of #18603.

`test_marker_as_MarkerStyle` ensures that a MarkerStyle instance can be
used as the marker argument to plot, scatter, and errorbar.